/*
 * Copyright 2026 The AI Crew Suite Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Metrics accounting block tracking generative model utilization data.
 * Used across sub-agents and monitoring services for resource tracking and audit logs.
 */
export interface UsageMetadata {
  /**
   * Complete metric compilation of total tokens processed (input + output).
   */
  readonly total_tokens: number;

  /**
   * Total number of newly generated response text tokens generated by the core model engine.
   */
  readonly output_tokens: number;

  /**
   * Total number of contextual or engineering text prompt tokens submitted to the underlying service endpoint.
   */
  readonly input_tokens: number;
}
